apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      db: postgres
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        db: postgres
    spec:
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres-db
          image: postgres:alpine
          resources:
            requests:
              cpu: 500m
              memory: 400Mi
            limits:
              cpu: "1.0"
              memory: 1Gi
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - mountPath: /postgres
              name: postgresdata
