apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: pouchfi
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    - protocol: 'TCP'
      port: 443
      targetPort: 443
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pouchfi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pouchfi
      tier: backend
  template:
    metadata:
      labels:
        app: pouchfi
        tier: backend
    spec:
      containers:
        - name: pouchfi-node
          image: thedumebi/pouchfi:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3005
            periodSeconds: 10
            initialDelaySeconds: 5
        # - name: ...
        #   image: ...
