version: '3'
services:
  api:
    # build: .
    image: thedumebi/pouchfi:1.0.0
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_PORT=5432
      - PG_HOST=postgres
    volumes:
      - ./:/app
      - /app/node_modules/bcrypt/
    ports:
      - '3005:3005'
    depends_on:
      - postgres
      - redis
    command: "npm run start"
  redis:
    image: redis:7.0.7
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data
  postgres:
    image: postgres:13.9
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ABcd12..
      - POSTGRES_DB=pouchfi
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
  cache:
