apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: 'TCP'
      port: 3005
      targetPort: 3005
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pouchfi-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: pouchfi-node
          image: thedumebi/pouchfi:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3005
            periodSeconds: 10
            initialDelaySeconds: 5
          envFrom:
            - configMapRef:
                name: pouchfi-env
          volumeMounts:
            - mountPath: /app/uploads
              name: pouchfi-uploads
            - mountPath: /app
              name: auth-keys
              readOnly: true
            # - mountPath: /app/node_modules/bcrypt
            #   name: bcrypt
      volumes:
        - name: pouchfi-uploads
          persistentVolumeClaim:
            claimName: pouchfi-pvc
        - name: auth-keys
          secret:
            secretName: auth-keys
        # - name: bcrypt
        #   emptyDir: {}
