apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis-config: |
    maxmemory 1Gb
    maxmemory-policy allkeys-lru
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:7.0.7
    command:
      - redis-server
      - "/redis-master/redis.conf"
    ports:
    - containerPort: 6379
    resources:
      limits:
        memory: 1Gi
        cpu: "0.1"
    volumeMounts:
    - mountPath: /redis-master
      name: config
    - mountPath: /data
      name: data
      readOnly: false
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pouchfi-pvc
    - name: config
      configMap:
        name: redis-config
        items:
        - key: redis-config
          path: redis.conf
