apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    db: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      db: postgres
  template:
    metadata:
      labels:
        db: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.9
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 500m
              memory: 400Mi
            limits:
              cpu: "1.0"
              memory: 1Gi
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pouchfi-env
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pvc
