# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dev

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: self-hosted
    env:
      PRIVATE_KEY: ${{ secrets.S_PRI_KEY }}
      PUBLIC_KEY: ${{ secrets.S_PUB_KEY }}

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Create Keys
        run: base64 -d <<< $PRIVATE_KEY > private.key
      - run: base64 -d <<< $PUBLIC_KEY > public.key

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Rebuild package
        run: npm rebuild sharp

      - name: Restart server
        run: pm2 restart pouchfi
